name: Build

on: push

jobs:

  x86:
    name: x86
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux \
                           libc6-dev-i386 valgrind \
                           libgcc-s1:i386 libc6-dbg:i386
      - name: Build (BIOS)
        run: |
          curl http://ca.ipxe.org/ca.crt -o src/ca.crt
          make -j 4 -C src EMBED=embed.ipxe TRUST=ca.crt DEBUG=x509,ocsp \
               bin/ipxe.lkrn \
               bin/ipxe.dsk \
               bin/ipxe.pxe \
               bin/ipxe.usb \
               bin/undionly.kpxe \
               bin-x86_64-efi/ipxe.efi
          src/util/genfsimg -o src/bin/iPXE.iso src/bin/ipxe.lkrn src/bin-x86_64-efi/ipxe.efi
      # - name: Build (Everything)
      #   run: |
      #     make -j 4 -C src everything
      # - name: Test
      #   run: |
      #     valgrind ./src/bin-i386-linux/tests.linux
      #     valgrind ./src/bin-x86_64-linux/tests.linux
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x86
          path: |
           ./src/bin
           ./src/bin-*
           !./src/**/*.a
           !./src/**/*.o
           !./src/**/*.d
           !./src/**/*.tmp
           !./src/**/*.map

  arm64:
    if: false
    name: ARM64
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux gcc-aarch64-linux-gnu
      - name: Build
        run: |
          curl http://ca.ipxe.org/ca.crt -o src/ca.crt
          make -j 4 -C src CROSS=aarch64-linux-gnu- EMBED=embed.ipxe TRUST=ca.crt DEBUG=x509,ocsp \
               bin-arm64-efi/ipxe.efi \
               bin-arm64-efi/ipxe.usb \
               bin-arm64-efi/ipxe.iso
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arm64
          path: |
           ./src/bin
           ./src/bin-*
           !./src/**/*.a
           !./src/**/*.o
           !./src/**/*.d
           !./src/**/*.tmp
           !./src/**/*.map